apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: fint-core-consumer-deployer-config
    namespace: fint-core
    files:
      - config.yaml
labels:
  - pairs:
      test: asdf123