apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fint-core-consumer-deployer-role
rules:
  - apiGroups: ["fintlabs.no"]
    resources: ["applications"]
    verbs: ["get", "create", "delete", "update"]
