apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fint-core-consumer-deployer-role-binding
subjects:
  - kind: ServiceAccount
    name: fint-core-consumer-deployer-sa
    namespace: fint-core
roleRef:
  kind: ClusterRole
  name: fint-core-consumer-deployer-role
  apiGroup: rbac.authorization.k8s.io
