apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-deployer
  template:
    metadata:
      labels:
        app: consumer-deployer
    spec:
      containers:
        - image: ghcr.io/fintlabs/fint-core-consumer-deployer:v1.0.0
          name: consumer
          ports:
            - containerPort: 8080
      serviceAccountName: consumer-deployer-sa