apiVersion: apps/v1
kind: Deployment
metadata:
  name: fint-core-consumer-deployer
  namespace: fint-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fint-core-consumer-deployer
  template:
    metadata:
      labels:
        app: fint-core-consumer-deployer
    spec:
      containers:
        - image: ghcr.io/fintlabs/fint-core-consumer-deployer:v1.0.0-rc-4
          name: consumer
          ports:
            - containerPort: 8080
      serviceAccountName: fint-core-consumer-deployer-sa