apiVersion: v1
kind: Service
metadata:
  name: fint-core-consumer-deployer
  namespace: fint-core
spec:
  selector:
    app: fint-core-consumer-deployer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP