apiVersion: v1
kind: Service
metadata:
  name: consumer-deployer-service
  namespace: default
spec:
  selector:
    app: consumer-deployer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP